INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Afghanistan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Albania');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Algeria');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('American Samoa');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Andorra');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Angola');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Anguilla');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Antigua and Barbuda');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Argentina');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Armenia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Aruba');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Australia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Austria');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Azerbaijan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Bahamas');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Bahrain');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Bangladesh');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Barbados');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Belarus');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Belgium');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Belize');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Benin');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Bermuda');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Bhutan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Bolivia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Bosnia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Botswana');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Brazil');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('British Virgin Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Brunei');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Bulgaria');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Burkina Faso');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Burundi');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Cambodia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Cameroon');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Canada');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Cape Verde');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Cayman Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Central African Republic');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Chad');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Chile');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('China');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Christmas Island');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Colombia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Comoros');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Cook Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Costa Rica');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Côte d\'Ivoire');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Croatia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Cuba');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Cyprus');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Czech Republic');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Democratic Republic of the Congo');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Denmark');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Djibouti');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Dominica');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Dominican Republic');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Ecuador');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Egypt');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('El Salvador');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Equatorial Guinea');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Eritrea');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Estonia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Ethiopia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Falkland Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Faroe Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Fiji');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Finland');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('France');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('French Polynesia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Gabon');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Gambia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Georgia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Germany');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Ghana');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Gibraltar');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Greece');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Greenland');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Grenada');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Guam');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Guatemala');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Guinea');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Guinea Bissau');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Guyana');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Haiti');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Honduras');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Hong Kong');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Hungary');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Iceland');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('India');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Indonesia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Iran');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Iraq');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Ireland');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Israel');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Italy');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Jamaica');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Japan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Jordan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Kazakhstan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Kenya');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Kiribati');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Kuwait');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Kyrgyzstan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Laos');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Latvia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Lebanon');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Lesotho');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Liberia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Libya');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Liechtenstein');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Lithuania');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Luxembourg');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Macao');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Macedonia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Madagascar');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Malawi');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Malaysia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Maldives');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Mali');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Malta');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Marshall Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Martinique');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Mauritania');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Mauritius');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Mexico');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Micronesia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Moldova');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Monaco');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Mongolia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Montserrat');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Morocco');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Mozambique');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Myanmar');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Namibia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Nauru');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Nepal');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Netherlands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Netherlands Antilles');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('New Zealand');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Nicaragua');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Niger');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Nigeria');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Niue');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Norfolk Island');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('North Korea');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Norway');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Oman');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Pakistan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Palau');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Panama');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Papua New Guinea');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Paraguay');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Peru');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Philippines');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Pitcairn Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Poland');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Portugal');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Puerto Rico');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Qatar');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Republic of the Congo');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Romania');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Russian Federation');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Rwanda');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Saint Kitts and Nevis');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Saint Lucia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Saint Pierre');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Saint Vicent and the Grenadines');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Samoa');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('San Marino');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Sao Tomé and Príncipe');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Saudi Arabia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Senegal');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Serbia and Montenegro');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Seychelles');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Sierra Leone');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Singapore');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Slovakia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Slovenia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Soloman Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Somalia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('South Africa');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('South Georgia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('South Korea');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Soviet Union');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Spain');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Sri Lanka');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Sudan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Suriname');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Swaziland');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Sweden');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Switzerland');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Syria');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Taiwan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Tajikistan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Tanzania');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Thailand');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Tibet');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Timor-Leste');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Togo');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Tonga');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Trinidad and Tobago');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Tunisia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Turkey');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Turkmenistan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Turks and Caicos Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Tuvalu');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('UAE');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Uganda');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Ukraine');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('United Kingdom');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('United States of America');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Uruguay');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('US Virgin Islands');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Uzbekistan');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Vanuatu');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Vatican City');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Venezuela');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Vietnam');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Wallis and Futuna');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Yemen');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Zambia');
INSERT INTO `mascref`.`app_country` (`name`) VALUES ('Zimbabwe');