# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectedConfidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='data_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.DataCollectedConfidence'),
            preserve_default=False,
        ),
    ]
