# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160708_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='domain',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
